### ISSUE TITLE
Feature 1: User can view movies 

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Cinematique#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view movies

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view list of movies in the theater today. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MB 1 SS](https://user-images.githubusercontent.com/97069037/163897133-3bbc93b5-382e-4e69-8462-53604b56f62e.PNG)

![Feature 1 SS](https://user-images.githubusercontent.com/97069037/163855419-070132e8-6917-40d4-bbe0-29343df18384.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure the user is able to see current movies in the theater by getting IMDB API using XMLHttpRequest()
- [x] Make sure the mobile version has two movies per row by setting media type and screen width
- [x] Make sure the desktop version has two movies per row by using flex and flex-wrap
- [x] Make two tabs for Movies and Entries
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
