### ISSUE TITLE
Feature 6: User can delete reviews

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Cinematique#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete reviews

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to delete reviews they created previously

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 6 SS](https://user-images.githubusercontent.com/97069037/164568323-bceecaf4-2d1e-4c63-a70a-86736be46ff8.PNG)
![MB 6 SS](https://user-images.githubusercontent.com/97069037/164568340-379ec757-bffa-44eb-b423-7b89318b01c8.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a click target on "delete" so that it is visible when user is trying to edit their review
- [x] Display confirmation modal to ask if they want to delete that review or not 
- [x] Hide modal when user clicks no
- [x] delete review if user clicks yes 
- [x] make sure user can see the review list after deleting their review

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
