### ISSUE TITLE
Feature 2: User can view details

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Cinematique#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of the movie clicked

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to see details of the movie that they clicked. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MB 2 SS](https://user-images.githubusercontent.com/97069037/163858085-56535cd3-c066-4557-9736-b43069b8183c.PNG)
![Feature 2 SS](https://user-images.githubusercontent.com/97069037/164112127-e35a7eaf-9008-48c6-a410-fc1d803e5149.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a layout for info page in HTML file
- [x] Add a "Back" button so that user can go back to the movie list
- [x] Create a DOM tree for the info page so movie has all the details it needs to display 
- [x] Listen for click events on images to display details if the user clicks on the image 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
