### ISSUE TITLE
Feature 3: User can add reviews

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Cinematique#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add reviews on current movies

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to write their own personal review 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature 3 SS](https://user-images.githubusercontent.com/97069037/164343077-3096e3d7-e0a6-4d2b-8ece-9c05fd3c2db9.PNG)

![MB 3 SS](https://user-images.githubusercontent.com/97069037/164343086-86b11f0d-23c0-4245-8ada-505010cc4a96.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a layout for review page in the HTML file
- [x] Listen for the click event on the "add review" button so that it goes to the "reviews page" when the user clicks add review
- [x] Make sure there is a new review being added whenever user clicks add review
- [x] Make sure the user is able to see all the reviews when they click reviews tab
- [x] If there's no reviews, display a message saying there's no review yet. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
