### ISSUE TITLE
Feature 5: User can edit reviews

### ISSUE THREAD

**Issue by michael-suh** [michael-suh/Cinematique#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit reviews

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to edit reviews they've written

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![MB 5 SS](https://user-images.githubusercontent.com/97069037/164561373-4a659954-18f0-4326-a341-bc19f0542cb2.PNG)
![Feature 5 SS](https://user-images.githubusercontent.com/97069037/164561392-e559895e-2f0a-4bf7-a662-cc6ee505c34a.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an edit button below each review so that user can edit their reviews
- [x] make event delegation so user can 'click' the edit button
- [x] Edit previous functions so that user can save the edited review
- [x] Make sure that the reviews are updated on the reviews page when user clicks 'save' 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
